### PR TITLE
fixed removeFromValidationSummary to also remove from 'local' array

### PR DESCRIPTION
**Pull request by tlastad**
Your latest change broke the removeFromValidationSummary functionality for me. 
I think I've fixed it. (Works for me :) )

Check it out and see if it works as expected. 
If you could find a more elegant solution it would me much appreciated :)

### CODE REVIEW

**Comment by ghiscoding** [comment]
Oh yes sorry, this function was introduced by you and I forgot to do any check on it ;)

**Comment by tlastad** [comment]
:)

**Comment by ghiscoding** [comment]
Alright I just finished bumping the version to 1.3.16, time to go to work now... Thanks for the help ;)

**Comment by tlastad** [comment]
The thanks are all yours :)

**Pull request merged**
