### PR TITLE
Merge pull request #4 from ghiscoding/master

### PR DESCRIPTION
**Pull request by tlastad**
merge from master

### CODE REVIEW

**Comment by ghiscoding** [comment]
Hello, did you make a mistake on a pull request? I don't see any changes...

**Comment by tlastad** [comment]
Yes,  sorry...
 I ment to merge your changes into my fork. 
☺

Tommy 

On April 24, 2015 2:49:50 PM CEST, "Ghislain B." <notifications@github.com> wrote:
>Hello, did you make a mistake on a pull request? I don't see any
>changes...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ghiscoding/angular-validation/pull/31#issuecomment-95922961

-- 
K-9 Mail.

**Comment by ghiscoding** [comment]
Haha ok no problem... you might want to close the issue though ;)

**Comment by tlastad** [comment]
Yeah, sorry about that :)

**Comment by ghiscoding** [comment]
No problem, I like the fact that you helped me much in my code... have a nice weekend ;)

**Pull request closed without merging**
