### PR TITLE
Changes to alpha* and euro date

### PR DESCRIPTION
**Pull request by cwallervand**
Alpha validations now allows æ, Æ, ø and Ø.
Euro date now allows . as a seperator, e.g. 15.10.97

### CODE REVIEW

**Comment by ghiscoding** [comment]
Thanks for the addition, I will look it up tonight and update my Protractor tests to cover the changes before creating another version. I should probably add the dot notation for US format too.

**Comment by ghiscoding** [comment]
Good think I looked into updating my Protractor tests because you made an error in the date format. You cannot put your Regex as this `[.-/]` because the `-` in the middle is now interpreted as a range meaning you start with `.` and end with `/` and this is failing my tests badly since after your changes only the `.` dot notation is working. It took me a few minutes to find out what was happening, but anyway, the proper way to write it is this `[-/.]`, just by making the `-` as the first character is enough to exclude it from being a range.

I'm updating my code in consequence and will push a new revision once I'm done with Protractor tests :)

**Comment by ghiscoding** [comment]
Alright it's all good now.. if you like the project, you can click on the `Star`

Thanks for the help :)

**Comment by cwallervand** [comment]
Damn, sorry for causing bugs :/ I was looking for some jasmine tests or some such in the project, but didnt find any so I didnt know how to test it...havent used Protractor before.

**Comment by ghiscoding** [comment]
No problem, that is what the tests are for.. :)
Enjoy it, use it, make it your favorite

**Pull request merged**
